getBaseUri
Error: Fatal error: Call to undefined method Phalcon\Http\Uri::toString()

I see that the Uri class has the magic function, so we don't need add ```->toString()```